# Generated by Django 3.2.9 on 2021-11-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0002_remove_predio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='usuarios',
        ),
    ]
